interface="your wifi interface name"
driver=nl80211
ssid=JetsonAP
hw_mode=g
channel=6
auth_algs=1
wmm_enabled=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase="your password"
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
country_code=KR
